packages:
    - ./packages/*
    - ./tests/*
    - ./bench
    - ./examples/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    esbuild: true

catalogs:
    dep:
        es-toolkit: ^1.40.0
    dev:
        "@rsbuild/core": 2.0.0
        vite: 8.0.12
    peer:
        "@rsbuild/core": ^2.0.0
        vite: ^8.0.12
    test:
        vitest: ^4.1.8
        vite-tsconfig-paths: ^6.1.1
    example:
        hono: ^4.12.25

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/*"
